In [1]:
from fredapi import Fred
import pandas as pd
from config import fred_api_key
from pprint import pprint

# Initialize the Fred client
fred = Fred(api_key=fred_api_key)

In [2]:
states = {"United States": "USA",
         "Alabama": "AL",
         "Alaska": "AK",
         "Arizona": "AZ",
         "Arkansas": "AR",
         "California": "CA",
         "Colorado":"CO",
         "Connecticut": "CT",
         "Delaware": "DE",
         "District of Columbia": "DC",
         "Florida": "FL",
         "Georgia": "GA",
         "Hawaii": "HI",
         "Idaho": "ID",
         "Illinois": "IL", 
         "Indiana": "IN",
         "Iowa": "IA",
         "Kansas": "KS",
         "Kentucky": "KY",
         "Louisiana": "LA",
         "Maine": "ME",
         "Maryland": "MD",
         "Massachusetts":"MA",
         "Michigan": "MI",
         "Minnesota": "MN",
         "Mississippi": "MS",
         "Missouri": "MO",
         "Montana": "MT",
         "Nebraska": "NE",
         "Nevada": "NV",
         "New Hampshire": "NH",
         "New Jersey": "NJ",
         "New Mexico": "NM", 
         "New York": "NY",
         "North Carolina": "NC",
         "North Dakota": "ND",
         "Ohio": "OH",
         "Oklahoma": "OK",
         "Oregon": "OR",
         "Pennsylvania": "PA",
         "Rhode Island": "RI",
         "South Carolina": "SC",
         "South Dakota": "SD",
         "Tennessee": "TN",
         "Texas": "TX",
         "Utah": "UT",
         "Vermont": "VT",
         "Virginia": "VA",
         "Washington": "WA",
         "West Virginia": "WV",
         "Wisconsin": "WI",
         "Wyoming": "WY",
         }

In [3]:
# Dictionary to hold data for all states
home_value_data = {}

# Fetch data for each state
for state, abbreviation in states.items():
    # Construct the series ID for each state
    series_id = f"{abbreviation}UCSFRCONDOSMSAMID"

    # Fetch the series data from FRED
    home_value = fred.get_series(series_id, observation_start="2004-01-01", observation_end="2023-01-01")
    home_value_data[state] = home_value

# Convert the data to a DataFrame
home_value_df = pd.DataFrame(home_value_data)
home_value_df.index.name = "Date"
pprint(home_value_df)

            United States        Alabama         Alaska        Arizona  \
Date
2004-01-01  161415.797093  112468.897763  187235.313336  166981.743111
2004-02-01  162463.870016  112725.088423  187841.549097  167847.418906
2004-03-01  163620.161222  113012.039266  188271.790840  168900.513316
2004-04-01  164912.797589  113305.182222  189382.536002  170180.251404
2004-05-01  166368.365614  113666.681304  190588.147633  171738.808920
...                   ...            ...            ...            ...
2022-09-01  346524.037497  221833.821012  359570.006602  450909.855503
2022-10-01  345296.962654  221508.269570  358789.792135  444441.126123
2022-11-01  344289.471095  220962.332115  357870.882403  437424.716679
2022-12-01  343374.431911  220464.728518  357246.882426  430528.770336
2023-01-01  342175.250509  220039.961263  356353.357902  423639.118474

                 Arkansas     California       Colorado    Connecticut  \
Date
2004-01-01  101330.145359  320965.660495  222891.848203  240366.466568
2004-02-01  101783.232071  325732.847350  223182.101684  242095.673819
2004-03-01  102304.179582  331170.356031  223520.345262  243749.324603
2004-04-01  102880.788798  337412.489527  224019.582683  245757.604398
2004-05-01  103421.568193  344599.782061  224670.441514  248250.261007
...                   ...            ...            ...            ...
2022-09-01  197718.901413  746931.891976  554152.650140  350801.779308
2022-10-01  197528.856407  740263.699280  549260.627844  350169.808570
2022-11-01  197244.778127  735023.432331  545491.892457  350480.890451
2022-12-01  196869.760669  730531.584283  542291.714419  351115.957496
2023-01-01  196303.471887  723543.220095  538704.000549  351396.175150

                 Delaware  District of Columbia  ...   South Dakota  \
Date                                             ...
2004-01-01  197922.447840         267170.444443  ...  120966.245893
2004-02-01  199353.176577         270092.529977  ...  121415.468933
2004-03-01  200834.169881         273584.934185  ...  122002.587018
2004-04-01  202654.263263         277048.370050  ...  122502.409568
2004-05-01  204843.252789         281171.423631  ...  123091.200481
...                   ...                   ...  ...            ...
2022-09-01  365825.151866         638621.952803  ...  297511.632608
2022-10-01  365310.402942         632609.855106  ...  297143.781578
2022-11-01  364994.581221         628137.174126  ...  297103.057878
2022-12-01  365313.724720         625077.859511  ...  297208.520466
2023-01-01  365716.370809         622165.442564  ...  296821.366340

                Tennessee          Texas           Utah        Vermont  \
Date
2004-01-01  122685.992092  120843.533394  180548.766033  159287.338362
2004-02-01  123007.298345  121661.051633  180839.208311  160645.635537
2004-03-01  123363.249017  122955.182386  181171.778189  162105.970945
2004-04-01  123763.276144  124239.434257  181569.731315  163691.500174
2004-05-01  124167.724328  125300.686962  181787.254249  165682.582390
...                   ...            ...            ...            ...
2022-09-01  306082.547824  307161.115290  533392.544236  370578.720697
2022-10-01  304915.930013  306211.183227  526692.532855  369381.295394
2022-11-01  303676.170850  305209.158422  521271.741133  369015.072114
2022-12-01  302464.068315  303921.620903  516939.675556  368842.991700
2023-01-01  301274.147588  302222.798236  513102.814379  370052.920300

                 Virginia     Washington  West Virginia      Wisconsin  \
Date
2004-01-01  177558.177299  212860.778161   86900.603167  150926.440573
2004-02-01  179308.464022  214128.636011   87419.094513  151705.824485
2004-03-01  181345.555866  215461.768858   88034.036663  152507.819145
2004-04-01  183784.251765  217005.863589   88581.017025  153457.607735
2004-05-01  186704.735618  218988.123794   89089.913281  154662.247862
...                   ...            ...            ...            ...
2022-09-01  361388.220706  586096.817679  154831.425791  275925.211317
2022-10-01  360563.503409  579385.486153  154627.641532  275333.809269
2022-11-01  360324.952260  574864.664814  154434.551756  275322.100276
2022-12-01  360449.283339  571473.103378  154661.824257  275653.176755
2023-01-01  360462.426314  567051.221702  154388.745757  277065.651044

                  Wyoming
Date
2004-01-01  154013.426255
2004-02-01  154493.152088
2004-03-01  155126.857142
2004-04-01  155979.327633
2004-05-01  157153.052502
...                   ...
2022-09-01  332745.853127
2022-10-01  333095.320805
2022-11-01  333812.582534
2022-12-01  334299.301405
2023-01-01  333941.710092

[229 rows x 52 columns]

In [4]:
home_value_df.to_csv("Data/home_value.csv")