In [9]:
# Collecting data on housing prices in the United States

#Import Packages
from fredapi import Fred
import pandas as pd
from config1 import api_key
from pprint import pprint
import os
import csv

# Initialize Fred api with api_key
fred = Fred(api_key=api_key)

#Initializing the file output
file_to_output = os.path.join("Home_Value.csv")

In [10]:
# list of states
states = {"United States": "USA",
         "Alabama": "AL",
         "Alaska": "AK",
         "Arizona": "AZ",
         "Arkansas": "AR",
         "California": "CA",
         "Colorado":"CO",
         "Connecticut": "CT",
         "Delaware": "DE",
         "District of Columbia": "DC",
         "Florida": "FL",
         "Georgia": "GA",
         "Hawaii": "HI",
         "Idaho": "ID",
         "Illinois": "IL", 
         "Indiana": "IN",
         "Iowa": "IA",
         "Kansas": "KS",
         "Kentucky": "KY",
         "Louisana": "LA",
         "Maine": "ME",
         "Maryland": "MD",
         "Massachusetts":"MA",
         "Michigan": "MI",
         "Minnesota": "MN",
         "Mississippi": "MS",
         "Missour": "MO",
         "Montana": "MT",
         "Nebraska": "NE",
         "Nevada": "NV",
         "New Hampshire": "NH",
         "New Jersey": "NJ",
         "New Mexico": "NM", 
         "New York": "NY",
         "North Carolina": "NC",
         "North Dakota": "ND",
         "Ohio": "OH",
         "Oklahoma": "OK",
         "Oregon": "OR",
         "Pennsylvania": "PA",
         "Rhode Island": "RI",
         "South Carolina": "SC",
         "South Dakota": "SD",
         "Tennessee": "TN",
         "Texas": "TX",
         "Utah": "UT",
         "Vermont": "VT",
         "Virginia": "VA",
         "Washington": "WA",
         "West Virginia": "WV",
         "Wisconsin": "WI",
         "Wyoming": "WY",
         }

In [11]:
# Created a dictionary to store data on home values for each state
home_value_data = {}

# Collecting data on home values for each state
for state, abbreviation in states.items():
    # Construct the series ID
    series_id = f"{abbreviation}UCSFRCONDOSMSAMID"

    # Collecting the series data from FRED
    # From 2004 to present
    # URL is below for reference
    # https://api.stlouisfed.org/fred/series/observations?series_id={series_id}&api_key={api_key}&file_type=json
    home_value = fred.get_series(series_id, observation_start="2004-01-01")

    # Add the data to the dictionary
    home_value_data[state] = home_value

# Convert the data to a DataFrame
home_value_df = pd.DataFrame(home_value_data)

# Indexed the date
home_value_df.index.name = "Date"

In [12]:
# Print the DataFrame
pprint(home_value_df)

# Write to CSV file
home_value_df.to_csv("Home_Value.csv")

            United States        Alabama         Alaska        Arizona  \
Date
2004-01-01  161415.797093  112468.897763  187235.313336  166981.743111
2004-02-01  162463.870016  112725.088423  187841.549097  167847.418906
2004-03-01  163620.161222  113012.039266  188271.790840  168900.513316
2004-04-01  164912.797589  113305.182222  189382.536002  170180.251404
2004-05-01  166368.365614  113666.681304  190588.147633  171738.808920
...                   ...            ...            ...            ...
2024-05-01  358490.016311  227524.247038  363290.965144  432274.680739
2024-06-01  359051.100806  228061.268922  363854.251343  432533.104343
2024-07-01  359199.002432  228135.820387  364036.253448  432162.979260
2024-08-01  359442.147602  227995.823618  364120.059471  431359.869290
2024-09-01  359892.330217  227873.121697  364673.503983  430657.543546

                 Arkansas     California       Colorado    Connecticut  \
Date
2004-01-01  101330.145359  320965.660495  222891.848203  240366.466568
2004-02-01  101783.232071  325732.847350  223182.101684  242095.673819
2004-03-01  102304.179582  331170.356031  223520.345262  243749.324603
2004-04-01  102880.788798  337412.489527  224019.582683  245757.604398
2004-05-01  103421.568193  344599.782061  224670.441514  248250.261007
...                   ...            ...            ...            ...
2024-05-01  205896.930970  764707.162319  542918.099073  401491.607133
2024-06-01  206730.235098  767178.618740  542727.516817  403398.170324
2024-07-01  207159.230291  769174.440854  542427.979618  404912.797158
2024-08-01  207546.207005  770943.060728  542574.854415  406441.864296
2024-09-01  207626.788468  773239.117639  543500.473407  408201.270173

                 Delaware  District of Columbia  ...   South Dakota  \
Date                                             ...
2004-01-01  197922.447840         267170.444443  ...  120966.245893
2004-02-01  199353.176577         270092.529977  ...  121415.468933
2004-03-01  200834.169881         273584.934185  ...  122002.587018
2004-04-01  202654.263263         277048.370050  ...  122502.409568
2004-05-01  204843.252789         281171.423631  ...  123091.200481
...                   ...                   ...  ...            ...
2024-05-01  386560.209990         610515.235862  ...  306531.025094
2024-06-01  386830.584595         607440.550149  ...  306824.690717
2024-07-01  386417.123902         604398.509443  ...  306768.273498
2024-08-01  386519.200325         601682.706988  ...  307010.535770
2024-09-01  387158.400281         601519.022311  ...  307798.783874

                Tennessee          Texas           Utah        Vermont  \
Date
2004-01-01  122685.992092  120843.533394  180548.766033  159287.338362
2004-02-01  123007.298345  121661.051633  180839.208311  160645.635537
2004-03-01  123363.249017  122955.182386  181171.778189  162105.970945
2004-04-01  123763.276144  124239.434257  181569.731315  163691.500174
2004-05-01  124167.724328  125300.686962  181787.254249  165682.582390
...                   ...            ...            ...            ...
2024-05-01  319367.918462  302475.250490  518697.334077  395677.003125
2024-06-01  320352.089485  302243.927123  518355.289407  397105.533635
2024-07-01  320732.719405  301684.071632  517456.432249  396759.976718
2024-08-01  320507.222400  301269.529498  516881.755176  396336.393013
2024-09-01  320181.271654  301010.886207  517549.770831  395523.163104

                 Virginia     Washington  West Virginia      Wisconsin  \
Date
2004-01-01  177558.177299  212860.778161   86900.603167  150926.440573
2004-02-01  179308.464022  214128.636011   87419.094513  151705.824485
2004-03-01  181345.555866  215461.768858   88034.036663  152507.819145
2004-04-01  183784.251765  217005.863589   88581.017025  153457.607735
2004-05-01  186704.735618  218988.123794   89089.913281  154662.247862
...                   ...            ...            ...            ...
2024-05-01  387947.017497  587071.326297  164601.308284  302491.010264
2024-06-01  389466.481347  588415.061874  165730.883276  304060.266106
2024-07-01  390381.307395  588964.665940  166679.375349  304939.825318
2024-08-01  391307.648836  589475.534421  167259.074236  305877.340380
2024-09-01  392433.696400  591094.935804  167571.307415  306556.895591

                  Wyoming
Date
2004-01-01  154013.426255
2004-02-01  154493.152088
2004-03-01  155126.857142
2004-04-01  155979.327633
2004-05-01  157153.052502
...                   ...
2024-05-01  348244.039504
2024-06-01  349001.632364
2024-07-01  349521.144205
2024-08-01  350933.427970
2024-09-01  353249.781520

[249 rows x 52 columns]